### ISSUE TITLE
Phemex Handler - AccountInfo

### ISSUE THREAD

**Issue by Duskfen** [dominik-pm/BeeBots#3]
# Interfaces (/account):
## /
> to get the account data of the api-key's user 

Request Data:
```javascript
{
    
}
```
Response Data:
```javascript
{
    "userID": Number,
    "btcBalance": Number
}
```

Todo:
- [x] implement a query to get the info from the phemex api

Test cases:
- [x] test response data
- [x] test error codes (api key permissions, jwt)

## /openposition
> to get the current position

Request Data:
```javascript
{
    
}
```
Response Data:
```javascript
{
    "position": {
        "entryPrice": Number,
        "side": "Buy" | "Sell",
        "leverage": Number,
        "quantity": Number,
        "stopLoss": Number,
        "takeProfit": Number
    }
}
```

Todo:
- [x] implement a function to query all currently open positions

Test cases:
- [x] test response data
- [x] test error codes (api key, jwt)

## /openorders
> to get all open long/short orders

Request Data:
```javascript
{
    
}
```
Response Data:
```javascript
[
    "orderID": String,
    "side": "Buy" | "Sell",
    "type": String,
    "stopDirection": String,
    "quantity": Number,
    "price": Number,
    "status": String
]
```

Todo:
- [x] implement a function to query all currently open orders

Test cases:
- [x] test response data
- [x] test error codes (api key, jwt)

**Comment by dominik-pm** [comment]
will be removed -> changed so that the bothandler doesnt need to know the users balance -> phemexhandler manages everything
