### ISSUE TITLE
Backend - Frontend Interface

### ISSUE THREAD

**Issue by dfaltin** [dominik-pm/BeeBots#9]
# Interfaces (/bots):
## /overview
> to get a List of all current available Bots and the profit of them

Request Data:
```javascript
{

}
```
Response Data:
```javascript
{
    "bots": [
        {
            "BotsId": Number,
            "Name": String,
            "profit": Float //percent
        }
    ]
}
```
todo
- [x] TODO @dfaltin

test todo
- [x] test correctness of data when triggering API-Interface

**Comment by Duskfen** [comment]
moving /details to sprint 3
